### ISSUE TITLE
从目录添加歌曲错误

### ISSUE THREAD

**Issue by RuiDeLiu** [LXG-Shadow/SongRecogn#3]
![image](https://user-images.githubusercontent.com/59120275/121897941-7263f600-cd55-11eb-988c-239347c5d86c.png)
可以从文件添加歌曲，但是从dir添加就会报错

**Comment by RuiDeLiu** [comment]
已经使用管理员身份打开了pycharm

**Comment by aynakeya** [comment]
自行google [errno 13] permission denied

**Comment by RuiDeLiu** [comment]
谢谢大佬
