### ISSUE TITLE
无法成功识别歌曲，报数据库的错误

### ISSUE THREAD

**Issue by RuiDeLiu** [LXG-Shadow/SongRecogn#4]
[识别报错.docx](https://github.com/LXG-Shadow/SongRecogn/files/6648701/default.docx)
![image](https://user-images.githubusercontent.com/59120275/121902817-426b2180-cd5a-11eb-9bbd-f1fd33de764b.png)
![image](https://user-images.githubusercontent.com/59120275/121902856-4ac35c80-cd5a-11eb-9879-c1215a1d7db8.png)
![image](https://user-images.githubusercontent.com/59120275/121902893-544cc480-cd5a-11eb-8cd4-664d51127664.png)
第三方库都是安装的对应版本

**Comment by aynakeya** [comment]
要么增加mysql的最大连接数，要么config里面把mysql_max_connection改小

**Comment by RuiDeLiu** [comment]
谢谢大佬！
